# Generated by Django 4.2 on 2023-04-14 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='topping',
            new_name='toppings',
        ),
        migrations.AddField(
            model_name='food',
            name='is_publish',
            field=models.BooleanField(default=False, verbose_name='Is publish'),
        ),
        migrations.AddField(
            model_name='food',
            name='is_special',
            field=models.BooleanField(default=False, verbose_name='Is special'),
        ),
        migrations.AddField(
            model_name='food',
            name='is_vegan',
            field=models.BooleanField(default=False, verbose_name='Is vegan'),
        ),
        migrations.AddField(
            model_name='foodcategory',
            name='is_publish',
            field=models.BooleanField(default=False, verbose_name='Is publish'),
        ),
    ]
