# Generated by Django 4.2 on 2023-04-14 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_rename_topping_food_toppings_food_is_publish_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='price',
            field=models.IntegerField(max_length=6, verbose_name='Цена'),
        ),
    ]
